window.SRTS = [
  "_test.srt",
  "Morozko_Eng_1964.Srt",
  "Drei.Haselnuesse.fuer.Aschenbroedel.(Remastered).DVDRip.German.AC3.by.forever-english.srt",
  "jak-dostat-tatinka-do-polepsovny.eng.srt",
  "Jak vytrhnout velrybe stolicku (1977).eng.srt",
  "jakvyvest-pivo-eng.srt",
  "marecku.podejte.mi.pero.srt",
  "Pelisky-eng.srt",
  "Pelisky.1999.1080p.BluRay.DTS-HDMA.x264.srt",
  "perinbaba.txt",
  "popelka.srt",
  "Princezna se zlatou hvezdou.srt",
  "s-tebou-me-bavi-svet.srt",
  "Three Wishes Of Cinderella (Tri Orisky Pro Popelku) (1973) Kinobox.srt",
  "vesnicko.eng.srt",
  "vesnicko.ma.strediskova.cd1-xvidcz.english.sub",
  "vesnicko.ma.strediskova.cd1-xvidcz.sub",
  "vesnicko.ma.strediskova.cd2-xvidcz.sub",
  "Vesnicko Ma Strediskova (1985).srt",
  "kral.sokolu.dvdrip.xvid.czdub.cd1.srt",
  "kral.sokolu.dvdrip.xvid.czdub.cd2.srt",
  "sokoliar-tomas.srt",
  "jachyme-hod-ho.srt",
  "My Sweet Little Village (Vesnicko m+í strediskov+í) (1985) 1h 38m 14s @25fps.ENG.srt",
  "na.samote.u.lesa-kinobox.English.srt",
  "Na.Samote.U.Lesa-Kinobox.srt",
  "Obecna.skola.DVDrip.XviD.AC3-WoodoX.srt",
  "Pane, Vy Jste Vdova.English.srt",
  "Postriziny (1981) ENG.sub",
  "s.certy.nejsou.zerty.en.srt",
  "S certy nejsou zerty.srt",
  "slunce.seno.a.par.facek.cd1-kinobox.English.srt",
  "SlunceSenoAparFacek_ENG.srt",
  "Slunce, seno, erotika.srt",
  "slunce-seno-erotika-1991-cz.srt",
  "Slunce Seno Jahody_EN.srt",
  "snezenky.a.machri-kinobox.English.srt",
  "vesnicko.ma.strediskova.cd1-xvidcz.english.sub",
  "vesnicko.ma.strediskova.cd1-xvidcz.sub",
  "vesnicko.ma.strediskova.cd2-xvidcz.sub",
  "vesnicko-ma-strediskova.srt",
  "Vesnicko Ma Strediskova (1985).srt",
  "vrchni prchni-kinobox.txt",
  "Vrchni Prchni-Kinobox.txt",
  "Nothing-to-Declare(0000180315).srt"
];
