window.SRTS = [
  "_test.srt",
  "Morozko_Eng_1964.Srt",
  "Drei.Haselnuesse.fuer.Aschenbroedel.(Remastered).DVDRip.German.AC3.by.forever-english.srt",
  "jak-dostat-tatinka-do-polepsovny.eng.srt",
  "Jak vytrhnout velrybe stolicku (1977).eng.srt",
  "jakvyvest-pivo-eng.srt",
  "marecku.podejte.mi.pero.srt",
  "Pelisky-eng.srt",
  "Pelisky.1999.1080p.BluRay.DTS-HDMA.x264.srt",
  "perinbaba.txt",
  "popelka.srt",
  "Princezna se zlatou hvezdou.srt",
  "s-tebou-me-bavi-svet.srt",
  "Three Wishes Of Cinderella (Tri Orisky Pro Popelku) (1973) Kinobox.srt",
  "vesnicko.eng.srt",
  "vesnicko.ma.strediskova.cd1-xvidcz.english.sub",
  "vesnicko.ma.strediskova.cd1-xvidcz.sub",
  "vesnicko.ma.strediskova.cd2-xvidcz.sub",
  "Vesnicko Ma Strediskova (1985).srt"
];
